//! Integration coverage for resume/replay over the on-disk session fixtures.
//!
//! These lock the two ends of the resume path that a unit test cannot reach
//! together: (1) the fixtures under `tests/fixtures/tui/sessions/` are real,
//! `SessionManager`-readable JSONL session files (so the tmux validator can
//! `hand --resume <fixture>` them), and (2) replaying a loaded fixture through the
//! rt driver's `replay_blocks` produces the ordered scrollback the driver commits —
//! including the present-side error footnote a resumed `error-ended` session
//! surfaces (VAL-CHAT-029), which is otherwise only reachable live via a resume.
//!
//! The fixtures are (re)generated by the `gen_session_fixtures` example; this test
//! reads them back, so a format drift fails here rather than silently at tmux time.

use std::path::PathBuf;

use hand_coding_agent::SessionManager;
use hand_coding_agent::modes::interactive::rt_driver::replay::replay_blocks;
use hand_coding_agent::modes::interactive::theme::ThemePalette;
use ratatui::text::Line;

/// The default theme palette — replay colouring is asserted on text/ordering,
/// so the default (historical) palette is used throughout.
fn pal() -> ThemePalette {
    ThemePalette::default()
}

/// The path to a named session fixture.
fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/tui/sessions")
        .join(format!("{name}.jsonl"))
}

/// Load a fixture's transcript through the real `SessionManager` reader.
fn load_messages(name: &str) -> Vec<model::Message> {
    let sm = SessionManager::open(&fixture(name)).expect("fixture must open");
    sm.build_context()
}

/// The joined plain text of every replayed line, one line per newline.
fn joined(blocks: &[Vec<Line<'static>>]) -> String {
    blocks
        .iter()
        .flatten()
        .map(|l| {
            l.spans
                .iter()
                .map(|s| s.content.as_ref())
                .collect::<String>()
        })
        .collect::<Vec<_>>()
        .join("\n")
}

#[test]
fn every_fixture_is_a_readable_session_with_a_transcript() {
    for name in ["thinking-blocks", "error-ended", "multi-message-resume"] {
        assert!(fixture(name).exists(), "fixture {name} must exist on disk");
        let messages = load_messages(name);
        assert!(
            !messages.is_empty(),
            "fixture {name} must carry a transcript"
        );
    }
}

#[test]
fn multi_message_fixture_replays_in_order_with_tool_line_and_marker() {
    // VAL-CHAT-012: ordered replay + a dimmed [tool_name] line + the resumed marker.
    let messages = load_messages("multi-message-resume");
    let blocks = replay_blocks(&messages, "multi", false, 80, &pal());
    let out = joined(&blocks);

    let idx = |needle: &str| {
        out.find(needle)
            .unwrap_or_else(|| panic!("missing {needle} in:\n{out}"))
    };
    // The conversation lands in order.
    assert!(idx("list the files") < idx("I'll read the directory."));
    assert!(idx("I'll read the directory.") < idx("[bash]"));
    assert!(idx("[bash]") < idx("There are three files"));
    assert!(idx("There are three files") < idx("thanks"));
    assert!(idx("thanks") < idx("You're welcome!"));
    // The tool result is a bracketed one-liner carrying its body.
    assert!(out.contains("[bash] a.txt b.txt c.txt"), "tool line: {out}");
    // The resumed marker closes the replay, last.
    assert!(idx("You're welcome!") < idx("[resumed: multi]"));
}

#[test]
fn error_ended_fixture_replays_the_present_side_error_footnote() {
    // VAL-CHAT-029 present-side: a resumed session whose last assistant message
    // stopped with stop_reason=Error surfaces the red `Error: <msg>` footnote when
    // replayed. The fixture stores a real stopReason:"error" (not a mock mapping),
    // so this is the live path the runtime validator probes over the TUI.
    let messages = load_messages("error-ended");
    // Sanity: the loaded transcript really carries a stop_reason=Error assistant.
    let has_error_stop = messages.iter().any(|m| {
        matches!(
            m,
            model::Message::Assistant(a) if a.stop_reason == model::StopReason::Error
        )
    });
    assert!(
        has_error_stop,
        "the error-ended fixture must carry a stop_reason=Error assistant message"
    );

    let blocks = replay_blocks(&messages, "err", false, 80, &pal());
    let out = joined(&blocks);
    assert!(
        out.contains("Error: rate limit exceeded"),
        "replay must surface the present-side error footnote:\n{out}"
    );
    assert!(out.contains("partial output before the failure"), "{out}");
}

#[test]
fn thinking_fixture_replays_the_thinking_block_then_answer() {
    // VAL-CHAT-012 with thinking: the dim-italic thinking body precedes the answer
    // when expanded, and collapses to the static label when hidden.
    let messages = load_messages("thinking-blocks");

    let expanded = joined(&replay_blocks(&messages, "t", false, 80, &pal()));
    let think = expanded
        .find("Let me reason about this carefully.")
        .expect("thinking body present when expanded");
    let answer = expanded.find("The answer is 42.").expect("answer present");
    assert!(
        think < answer,
        "thinking must precede the answer:\n{expanded}"
    );

    let collapsed = joined(&replay_blocks(&messages, "t", true, 80, &pal()));
    assert!(
        collapsed.contains("Thinking..."),
        "collapsed shows the static label:\n{collapsed}"
    );
    assert!(
        !collapsed.contains("Let me reason about this carefully."),
        "collapsed thinking must not leak the body:\n{collapsed}"
    );
}
