//! Model registry and helpers. Mirrors pi-mono `packages/ai/src/models.ts`.
//!
//! Run `cargo run --bin generate_models` to regenerate `models.json`.

use crate::types::{Model, Usage, UsageCost};
use std::collections::HashMap;
use std::sync::OnceLock;

/// JSON content (generated by `cargo run --bin generate_models`).
pub const MODELS_JSON: &str = include_str!("models.json");

type Registry = HashMap<String, HashMap<String, Model>>;

fn registry() -> &'static Registry {
    static REGISTRY: OnceLock<Registry> = OnceLock::new();
    REGISTRY.get_or_init(|| serde_json::from_str(MODELS_JSON).unwrap_or_default())
}

/// Parsed models: provider key -> model_id -> Model.
pub fn models() -> Result<HashMap<String, HashMap<String, Model>>, serde_json::Error> {
    serde_json::from_str(MODELS_JSON)
}

/// Get a model by provider (string key) and model id.
#[inline]
pub fn get_model(provider: &str, model_id: &str) -> Option<Model> {
    registry()
        .get(provider)
        .and_then(|m| m.get(model_id))
        .cloned()
}

/// Get a model by provider enum and model id.
#[inline]
pub fn get_model_by_provider(
    provider: crate::types::KnownProvider,
    model_id: &str,
) -> Option<Model> {
    get_model(provider.as_str(), model_id)
}

/// All provider keys present in the registry.
pub fn get_provider_keys() -> Vec<String> {
    let mut keys: Vec<String> = registry().keys().cloned().collect();
    keys.sort();
    keys
}

/// All known providers that have at least one model in the registry.
pub fn get_providers() -> Vec<crate::types::KnownProvider> {
    registry()
        .keys()
        .filter_map(|k| crate::types::KnownProvider::from_str(k))
        .collect()
}

/// All models for a provider (by string key).
pub fn get_models(provider: &str) -> Vec<Model> {
    registry()
        .get(provider)
        .map(|m| m.values().cloned().collect())
        .unwrap_or_default()
}

/// All models for a provider (by enum).
pub fn get_models_by_provider(provider: crate::types::KnownProvider) -> Vec<Model> {
    get_models(provider.as_str())
}

/// Compute cost from model pricing and token usage, fill `usage.cost` and return it.
/// Model cost is $/million tokens; usage fields are token counts.
pub fn calculate_cost<'a>(model: &Model, usage: &'a mut Usage) -> &'a UsageCost {
    usage.cost.input = (model.cost.input / 1_000_000.0) * usage.input as f64;
    usage.cost.output = (model.cost.output / 1_000_000.0) * usage.output as f64;
    usage.cost.cache_read = (model.cost.cache_read / 1_000_000.0) * usage.cache_read as f64;
    usage.cost.cache_write = (model.cost.cache_write / 1_000_000.0) * usage.cache_write as f64;
    usage.cost.total =
        usage.cost.input + usage.cost.output + usage.cost.cache_read + usage.cost.cache_write;
    &usage.cost
}

/// Model IDs that support xhigh thinking level (e.g. certain OpenAI Codex models).
const XHIGH_MODEL_IDS: &[&str] = &["gpt-5.1-codex-max", "gpt-5.2", "gpt-5.2-codex"];

/// Whether this model supports xhigh thinking level.
#[inline]
pub fn supports_xhigh(model: &Model) -> bool {
    XHIGH_MODEL_IDS.contains(&model.id.as_str())
}

/// Compare two models by id and provider. Returns false if either is None.
pub fn models_are_equal(a: Option<&Model>, b: Option<&Model>) -> bool {
    match (a, b) {
        (Some(a), Some(b)) => a.id == b.id && a.provider == b.provider,
        _ => false,
    }
}
