//! Model registry and helpers. Mirrors pi-mono `packages/ai/src/models.ts`.
//!
//! Run `cargo run --bin generate_models` to regenerate `models.json`.

use crate::types::{Model, Usage, UsageCost};
use std::collections::HashMap;
use std::sync::OnceLock;

/// JSON content (generated by `cargo run --bin generate_models`).
pub const MODELS_JSON: &str = include_str!("models.json");

type Registry = HashMap<String, HashMap<String, Model>>;

fn registry() -> &'static Registry {
    static REGISTRY: OnceLock<Registry> = OnceLock::new();
    REGISTRY.get_or_init(|| serde_json::from_str(MODELS_JSON).unwrap_or_default())
}

/// Parsed models: provider key -> model_id -> Model.
pub fn models() -> Result<HashMap<String, HashMap<String, Model>>, serde_json::Error> {
    serde_json::from_str(MODELS_JSON)
}

/// Get a model by provider (string key) and model id.
#[inline]
pub fn get_model(provider: &str, model_id: &str) -> Option<Model> {
    registry()
        .get(provider)
        .and_then(|m| m.get(model_id))
        .cloned()
}

/// Get a model by provider enum and model id.
#[inline]
pub fn get_model_by_provider(
    provider: crate::types::KnownProvider,
    model_id: &str,
) -> Option<Model> {
    get_model(provider.as_str(), model_id)
}

/// All provider keys present in the registry.
pub fn get_provider_keys() -> Vec<String> {
    let mut keys: Vec<String> = registry().keys().cloned().collect();
    keys.sort();
    keys
}

/// All known providers that have at least one model in the registry.
pub fn get_providers() -> Vec<crate::types::KnownProvider> {
    registry()
        .keys()
        .filter_map(|k| crate::types::KnownProvider::from_str(k))
        .collect()
}

/// All models for a provider (by string key).
pub fn get_models(provider: &str) -> Vec<Model> {
    registry()
        .get(provider)
        .map(|m| m.values().cloned().collect())
        .unwrap_or_default()
}

/// All models for a provider (by enum).
pub fn get_models_by_provider(provider: crate::types::KnownProvider) -> Vec<Model> {
    get_models(provider.as_str())
}

/// Compute cost from model pricing and token usage, fill `usage.cost` and return it.
/// Model cost is $/million tokens; usage fields are token counts.
pub fn calculate_cost<'a>(model: &Model, usage: &'a mut Usage) -> &'a UsageCost {
    usage.cost.input = (model.cost.input / 1_000_000.0) * usage.input as f64;
    usage.cost.output = (model.cost.output / 1_000_000.0) * usage.output as f64;
    usage.cost.cache_read = (model.cost.cache_read / 1_000_000.0) * usage.cache_read as f64;
    usage.cost.cache_write = (model.cost.cache_write / 1_000_000.0) * usage.cache_write as f64;
    usage.cost.total =
        usage.cost.input + usage.cost.output + usage.cost.cache_read + usage.cost.cache_write;
    &usage.cost
}

/// Model IDs that support xhigh thinking level (e.g. certain OpenAI Codex models).
const XHIGH_MODEL_IDS: &[&str] = &["gpt-5.1-codex-max", "gpt-5.2", "gpt-5.2-codex"];

/// Whether this model supports xhigh thinking level.
#[inline]
pub fn supports_xhigh(model: &Model) -> bool {
    XHIGH_MODEL_IDS.contains(&model.id.as_str())
}

/// Compare two models by id and provider. Returns false if either is None.
pub fn models_are_equal(a: Option<&Model>, b: Option<&Model>) -> bool {
    match (a, b) {
        (Some(a), Some(b)) => a.id == b.id && a.provider == b.provider,
        _ => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{Cost, InputType, KnownApi, KnownProvider, Usage};

    fn test_model(id: &str, provider: KnownProvider) -> Model {
        Model {
            id: id.to_string(),
            name: "Test".to_string(),
            api: KnownApi::OpenAIResponses,
            provider,
            base_url: "https://example.com".to_string(),
            reasoning: false,
            input: vec![InputType::Text],
            cost: Cost {
                input: 1.0,
                output: 2.0,
                cache_read: 0.5,
                cache_write: 0.25,
            },
            context_window: 128,
            max_tokens: 64,
            headers: None,
            compat: None,
        }
    }

    #[test]
    fn models_parses_non_empty() {
        let parsed = models().expect("models json should parse");
        assert!(!parsed.is_empty());
    }

    #[test]
    fn provider_keys_are_sorted() {
        let parsed = models().expect("models json should parse");
        let mut expected: Vec<String> = parsed.keys().cloned().collect();
        expected.sort();
        assert_eq!(expected, get_provider_keys());
    }

    #[test]
    fn get_model_and_models_roundtrip() {
        let parsed = models().expect("models json should parse");
        let provider = get_provider_keys().first().cloned().expect("provider key");
        let model_id = parsed
            .get(&provider)
            .and_then(|m| m.keys().next())
            .cloned()
            .expect("model id");
        let via_get = get_model(&provider, &model_id).expect("get_model should find model");
        assert_eq!(via_get.id, model_id);
        let models = get_models(&provider);
        assert!(models.iter().any(|m| m.id == model_id));
    }

    #[test]
    fn calculate_cost_sets_breakdown_and_total() {
        let model = test_model("cost-test", KnownProvider::OpenAI);
        let mut usage = Usage {
            input: 2_000_000,
            output: 1_000_000,
            cache_read: 2_000_000,
            cache_write: 4_000_000,
            total_tokens: 0,
            cost: Default::default(),
        };
        let cost = calculate_cost(&model, &mut usage);
        assert!((cost.input - 2.0).abs() < f64::EPSILON);
        assert!((cost.output - 2.0).abs() < f64::EPSILON);
        assert!((cost.cache_read - 1.0).abs() < f64::EPSILON);
        assert!((cost.cache_write - 1.0).abs() < f64::EPSILON);
        assert!((cost.total - 6.0).abs() < f64::EPSILON);
    }

    #[test]
    fn supports_xhigh_checks_ids() {
        let xhigh = test_model("gpt-5.2", KnownProvider::OpenAI);
        let normal = test_model("gpt-4o", KnownProvider::OpenAI);
        assert!(supports_xhigh(&xhigh));
        assert!(!supports_xhigh(&normal));
    }

    #[test]
    fn models_are_equal_checks_id_and_provider() {
        let a = test_model("same", KnownProvider::OpenAI);
        let b = test_model("same", KnownProvider::OpenAI);
        let c = test_model("same", KnownProvider::Anthropic);
        let d = test_model("other", KnownProvider::OpenAI);
        assert!(models_are_equal(Some(&a), Some(&b)));
        assert!(!models_are_equal(Some(&a), Some(&c)));
        assert!(!models_are_equal(Some(&a), Some(&d)));
        assert!(!models_are_equal(Some(&a), None));
    }
}
