//! Model registry and helpers.
//!
//! Run `cargo run --bin generate_models` to regenerate `models.json`.

use crate::types::{Model, Usage, UsageCost};
use std::collections::HashMap;
use std::sync::{Arc, OnceLock, RwLock};

/// JSON content (generated by `cargo run --bin generate_models`).
pub const MODELS_JSON: &str = include_str!("models.json");

pub(crate) type Registry = HashMap<String, HashMap<String, Model>>;

/// Process-wide catalog cell. Initialized from the embedded baseline
/// (`MODELS_JSON`); the remote-refresh path may atomically swap in a newer
/// snapshot at runtime, so reads go through [`catalog_snapshot`] rather than
/// a `&'static` reference.
fn registry_cell() -> &'static RwLock<Arc<Registry>> {
    static REGISTRY: OnceLock<RwLock<Arc<Registry>>> = OnceLock::new();
    REGISTRY.get_or_init(|| {
        let baseline: Registry = serde_json::from_str(MODELS_JSON).unwrap_or_default();
        RwLock::new(Arc::new(baseline))
    })
}

/// Current catalog snapshot. Cheap — an `Arc` clone — so an in-flight read
/// is never invalidated by a concurrent swap from the refresh path.
pub(crate) fn catalog_snapshot() -> Arc<Registry> {
    registry_cell()
        .read()
        .unwrap_or_else(|poisoned| poisoned.into_inner())
        .clone()
}

/// Parsed models: provider key -> model_id -> Model.
pub fn models() -> Result<HashMap<String, HashMap<String, Model>>, serde_json::Error> {
    serde_json::from_str(MODELS_JSON)
}

/// Get a model by provider (string key) and model id.
#[inline]
pub fn get_model(provider: &str, model_id: &str) -> Option<Model> {
    catalog_snapshot()
        .get(provider)
        .and_then(|m| m.get(model_id))
        .cloned()
}

/// Get a model by provider enum and model id.
#[inline]
pub fn get_model_by_provider(provider: crate::types::Provider, model_id: &str) -> Option<Model> {
    get_model(provider.as_str(), model_id)
}

/// All provider keys present in the registry.
pub fn get_provider_keys() -> Vec<String> {
    let mut keys: Vec<String> = catalog_snapshot().keys().cloned().collect();
    keys.sort();
    keys
}

/// All known providers that have at least one model in the registry.
pub fn get_providers() -> Vec<crate::types::Provider> {
    catalog_snapshot()
        .keys()
        .filter_map(|k| crate::types::Provider::from_str(k))
        .collect()
}

/// All models for a provider (by string key).
pub fn get_models(provider: &str) -> Vec<Model> {
    catalog_snapshot()
        .get(provider)
        .map(|m| m.values().cloned().collect())
        .unwrap_or_default()
}

/// All models for a provider (by enum).
pub fn get_models_by_provider(provider: crate::types::Provider) -> Vec<Model> {
    get_models(provider.as_str())
}

/// Compute cost from model pricing and token usage, fill `usage.cost` and return it.
/// Model cost is $/million tokens; usage fields are token counts.
pub fn calculate_cost<'a>(model: &Model, usage: &'a mut Usage) -> &'a UsageCost {
    usage.cost.input = (model.cost.input / 1_000_000.0) * usage.input as f64;
    usage.cost.output = (model.cost.output / 1_000_000.0) * usage.output as f64;
    usage.cost.cache_read = (model.cost.cache_read / 1_000_000.0) * usage.cache_read as f64;
    usage.cost.cache_write = (model.cost.cache_write / 1_000_000.0) * usage.cache_write as f64;
    usage.cost.total =
        usage.cost.input + usage.cost.output + usage.cost.cache_read + usage.cost.cache_write;
    &usage.cost
}

/// Substrings that mark a model id as xhigh-capable. Substring match is
/// chosen so the full GPT-5.x reasoning family (`gpt-5.2-codex-max`,
/// `gpt-5.3-mini`, ...) and the namespaced OpenRouter DeepSeek ids
/// (`deepseek/deepseek-v4-pro`) all match without listing every variant.
const XHIGH_MODEL_ID_PATTERNS: &[&str] = &[
    "gpt-5.1-codex-max",
    "gpt-5.2",
    "gpt-5.3",
    "gpt-5.4",
    "gpt-5.5",
    "deepseek-v4-pro",
    "deepseek-v4-flash",
    // Anthropic Opus 4.6 and 4.7 map xhigh to adaptive effort on the
    // Anthropic Messages API. Match by id (both dashed and dotted
    // variants are seen across catalogs / proxies) so OpenRouter's
    // `anthropic/claude-opus-4.6` and the direct
    // `claude-opus-4-6-20251001` ids both surface as xhigh-capable.
    "opus-4-6",
    "opus-4.6",
    "opus-4-7",
    "opus-4.7",
];

/// Whether this model supports xhigh thinking level.
#[inline]
pub fn supports_xhigh(model: &Model) -> bool {
    XHIGH_MODEL_ID_PATTERNS
        .iter()
        .any(|needle| model.id.contains(needle))
}

/// Ordered set of thinking levels surfaced to callers, where `None`
/// represents the "off" sentinel (no reasoning) and each `Some` variant
/// is a budget tier from minimal up through xhigh.
const EXTENDED_THINKING_LEVELS: &[Option<crate::types::ThinkingLevel>] = &[
    None,
    Some(crate::types::ThinkingLevel::Minimal),
    Some(crate::types::ThinkingLevel::Low),
    Some(crate::types::ThinkingLevel::Medium),
    Some(crate::types::ThinkingLevel::High),
    Some(crate::types::ThinkingLevel::Xhigh),
];

/// Translate the `None = off` / `Some(level)` representation into the
/// lower-case key that `Model.thinking_level_map` uses on disk so the
/// helpers below can consult per-model overrides.
fn thinking_level_map_key(level: Option<crate::types::ThinkingLevel>) -> &'static str {
    match level {
        None => "off",
        Some(crate::types::ThinkingLevel::Minimal) => "minimal",
        Some(crate::types::ThinkingLevel::Low) => "low",
        Some(crate::types::ThinkingLevel::Medium) => "medium",
        Some(crate::types::ThinkingLevel::High) => "high",
        Some(crate::types::ThinkingLevel::Xhigh) => "xhigh",
    }
}

/// Return the thinking levels this model accepts. `None` in the list is
/// the "off" sentinel; reasoning models always include it. Non-reasoning
/// models return exactly `[None]`.
///
/// When the model carries an explicit `thinking_level_map`, each level
/// is filtered by that table: a `Some(None)` entry (JSON `null`) marks
/// a level as unsupported, while a missing key keeps the level for the
/// general tiers and drops `xhigh` (matching the upstream `xhigh
/// requires an explicit entry` rule). Without a map, every tier is
/// admitted and `xhigh` falls back to the substring-based
/// [`supports_xhigh`] heuristic so existing GPT-5.x / Opus 4.6+ /
/// DeepSeek V4 catalog entries keep advertising xhigh.
pub fn get_supported_thinking_levels(model: &Model) -> Vec<Option<crate::types::ThinkingLevel>> {
    if !model.reasoning {
        return vec![None];
    }
    EXTENDED_THINKING_LEVELS
        .iter()
        .copied()
        .filter(|level| {
            let key = thinking_level_map_key(*level);
            match &model.thinking_level_map {
                Some(map) => match map.get(key) {
                    Some(None) => false,
                    Some(Some(_)) => true,
                    None => !matches!(level, Some(crate::types::ThinkingLevel::Xhigh)),
                },
                None => match level {
                    Some(crate::types::ThinkingLevel::Xhigh) => supports_xhigh(model),
                    _ => true,
                },
            }
        })
        .collect()
}

/// Clamp `requested` to the closest level this model actually supports.
/// Search first by walking up (toward `xhigh`) and then back down toward
/// `off`. If the requested level is unrecognised, fall back to the
/// model's first supported level (or `off`).
pub fn clamp_thinking_level(
    model: &Model,
    requested: Option<crate::types::ThinkingLevel>,
) -> Option<crate::types::ThinkingLevel> {
    let available = get_supported_thinking_levels(model);
    if available.contains(&requested) {
        return requested;
    }
    let Some(requested_index) = EXTENDED_THINKING_LEVELS
        .iter()
        .position(|l| *l == requested)
    else {
        return available.first().copied().flatten();
    };
    for level in &EXTENDED_THINKING_LEVELS[requested_index..] {
        if available.contains(level) {
            return *level;
        }
    }
    for level in EXTENDED_THINKING_LEVELS[..requested_index].iter().rev() {
        if available.contains(level) {
            return *level;
        }
    }
    None
}

/// Compare two models by id and provider. Returns false if either is None.
pub fn models_are_equal(a: Option<&Model>, b: Option<&Model>) -> bool {
    match (a, b) {
        (Some(a), Some(b)) => a.id == b.id && a.provider == b.provider,
        _ => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{Api, Cost, InputType, Provider, ThinkingLevel, Usage};

    fn test_model(id: &str, provider: Provider) -> Model {
        Model {
            id: id.to_string(),
            name: "Test".to_string(),
            api: Api::OpenAIResponses,
            provider,
            base_url: "https://example.com".to_string(),
            reasoning: false,
            input: vec![InputType::Text],
            cost: Cost {
                input: 1.0,
                output: 2.0,
                cache_read: 0.5,
                cache_write: 0.25,
            },
            context_window: 128,
            max_tokens: 64,
            headers: None,
            compat: None,
            thinking_level_map: None,
        }
    }

    /// The committed catalog must equal its own re-serialization through the
    /// same (lossy) f64 parser the runtime uses, so `generate_models`
    /// produces a deterministically key-ordered, churn-free file and the
    /// on-disk values match what every consumer actually loads. If this
    /// fails, regenerate with `cargo run -p model --bin generate_models`.
    #[test]
    fn catalog_json_is_canonical() {
        use std::collections::BTreeMap;
        let parsed: BTreeMap<String, BTreeMap<String, Model>> =
            serde_json::from_str(MODELS_JSON).expect("catalog should parse");
        let canonical = serde_json::to_string_pretty(&parsed).expect("catalog should serialize");
        assert_eq!(
            MODELS_JSON.trim_end(),
            canonical.trim_end(),
            "models.json is not canonical (key-order or float-fold drift); \
             regenerate with `cargo run -p model --bin generate_models`"
        );
    }

    /// The hot-swappable registry must serve reads from the embedded
    /// baseline until something installs a newer catalog.
    #[test]
    fn catalog_snapshot_serves_baseline() {
        let snap = catalog_snapshot();
        assert!(!snap.is_empty(), "snapshot should expose the baseline catalog");
        let provider = get_provider_keys()
            .into_iter()
            .next()
            .expect("at least one provider");
        assert!(
            snap.get(&provider).is_some_and(|m| !m.is_empty()),
            "snapshot and public read API must agree"
        );
    }

    #[test]
    fn models_parses_non_empty() {
        let parsed = models().expect("models json should parse");
        assert!(!parsed.is_empty());
    }

    #[test]
    fn provider_keys_are_sorted() {
        let parsed = models().expect("models json should parse");
        let mut expected: Vec<String> = parsed.keys().cloned().collect();
        expected.sort();
        assert_eq!(expected, get_provider_keys());
    }

    #[test]
    fn get_model_and_models_roundtrip() {
        let parsed = models().expect("models json should parse");
        let provider = get_provider_keys().first().cloned().expect("provider key");
        let model_id = parsed
            .get(&provider)
            .and_then(|m| m.keys().next())
            .cloned()
            .expect("model id");
        let via_get = get_model(&provider, &model_id).expect("get_model should find model");
        assert_eq!(via_get.id, model_id);
        let models = get_models(&provider);
        assert!(models.iter().any(|m| m.id == model_id));
    }

    /// Kimi's upstream API gates traffic on a recognised `User-Agent`
    /// string. Without it the SDK is rejected as an unknown client.
    /// Every Kimi-for-coding model in the catalog must therefore
    /// carry the `KimiCLI/1.5` UA header in its baked-in metadata.
    #[test]
    fn kimi_coding_models_carry_user_agent_header() {
        let kimi_models = get_models("kimi-coding");
        assert!(
            !kimi_models.is_empty(),
            "expected at least one kimi-coding model in the catalog"
        );
        for m in kimi_models {
            let headers = m
                .headers
                .as_ref()
                .unwrap_or_else(|| panic!("kimi model {} missing headers", m.id));
            let ua = headers
                .get("User-Agent")
                .unwrap_or_else(|| panic!("kimi model {} missing User-Agent header", m.id));
            assert_eq!(ua, "KimiCLI/1.5", "model {} has wrong UA: {ua}", m.id);
        }
    }

    #[test]
    fn calculate_cost_sets_breakdown_and_total() {
        let model = test_model("cost-test", Provider::OpenAI);
        let mut usage = Usage {
            input: 2_000_000,
            output: 1_000_000,
            cache_read: 2_000_000,
            cache_write: 4_000_000,
            total_tokens: 0,
            cost: Default::default(),
        };
        let cost = calculate_cost(&model, &mut usage);
        assert!((cost.input - 2.0).abs() < f64::EPSILON);
        assert!((cost.output - 2.0).abs() < f64::EPSILON);
        assert!((cost.cache_read - 1.0).abs() < f64::EPSILON);
        assert!((cost.cache_write - 1.0).abs() < f64::EPSILON);
        assert!((cost.total - 6.0).abs() < f64::EPSILON);
    }

    #[test]
    fn supports_xhigh_checks_ids() {
        let xhigh = test_model("gpt-5.2", Provider::OpenAI);
        let normal = test_model("gpt-4o", Provider::OpenAI);
        assert!(supports_xhigh(&xhigh));
        assert!(!supports_xhigh(&normal));
    }

    /// xhigh recognition must extend to the full GPT-5.x reasoning family
    /// and the DeepSeek V4 reasoning models on every provider, including
    /// OpenRouter where the id is namespaced (`deepseek/...`). Hardcoded
    /// exact-match misses both the variant suffixes (`gpt-5.3-mini`,
    /// `gpt-5.2-codex-max`) and the namespaced OpenRouter ids.
    #[test]
    fn supports_xhigh_extends_to_gpt5_family_and_deepseek_v4() {
        for id in [
            "gpt-5.2",
            "gpt-5.2-codex",
            "gpt-5.3",
            "gpt-5.3-mini",
            "gpt-5.4",
            "gpt-5.5-preview",
            "deepseek-v4-pro",
            "deepseek-v4-flash",
            "deepseek/deepseek-v4-flash",
            "deepseek/deepseek-v4-pro",
        ] {
            let m = test_model(id, Provider::OpenAI);
            assert!(supports_xhigh(&m), "{id} should support xhigh");
        }
    }

    #[test]
    fn supports_xhigh_excludes_unrelated_ids() {
        for id in ["gpt-4o", "claude-sonnet-4", "deepseek-v3", "gpt-5.0-mini"] {
            let m = test_model(id, Provider::OpenAI);
            assert!(!supports_xhigh(&m), "{id} should NOT support xhigh");
        }
    }

    /// Anthropic Opus 4.6 (and its namespaced openrouter id) supports
    /// xhigh and must be recognised across every wire-form id the
    /// catalog uses. The pattern keys off the version stub so future
    /// 4.6 sub-variants (`claude-opus-4-6-20251001`,
    /// `claude-opus-4.6-thinking`, OpenRouter
    /// `anthropic/claude-opus-4.6`) all match.
    #[test]
    fn supports_xhigh_recognises_opus_4_6_variants() {
        for id in [
            "claude-opus-4-6",
            "claude-opus-4-6-20251001",
            "claude-opus-4.6",
            "claude-opus-4.6-thinking",
            "anthropic/claude-opus-4.6",
        ] {
            let m = test_model(id, Provider::Anthropic);
            assert!(supports_xhigh(&m), "{id} should support xhigh");
        }
    }

    /// Opus 4.7 also supports xhigh — adaptive thinking on the newer
    /// Anthropic generation, with `xhigh` as the native effort name
    /// (not `max` like 4.6). Recognition must cover both dashed and
    /// dotted ids and the namespaced OpenRouter form.
    #[test]
    fn supports_xhigh_recognises_opus_4_7_variants() {
        for id in [
            "claude-opus-4-7",
            "claude-opus-4-7-20260101",
            "claude-opus-4.7",
            "anthropic/claude-opus-4.7",
        ] {
            let m = test_model(id, Provider::Anthropic);
            assert!(supports_xhigh(&m), "{id} should support xhigh");
        }
    }

    /// Older Opus generations stay below the xhigh threshold so we
    /// don't accidentally clamp a non-thinking model's effort.
    #[test]
    fn supports_xhigh_excludes_older_opus_generations() {
        for id in [
            "claude-opus-4",
            "claude-opus-4-1",
            "claude-opus-3-5",
            "claude-opus-3",
        ] {
            let m = test_model(id, Provider::Anthropic);
            assert!(!supports_xhigh(&m), "{id} must NOT support xhigh");
        }
    }

    #[test]
    fn models_are_equal_checks_id_and_provider() {
        let a = test_model("same", Provider::OpenAI);
        let b = test_model("same", Provider::OpenAI);
        let c = test_model("same", Provider::Anthropic);
        let d = test_model("other", Provider::OpenAI);
        assert!(models_are_equal(Some(&a), Some(&b)));
        assert!(!models_are_equal(Some(&a), Some(&c)));
        assert!(!models_are_equal(Some(&a), Some(&d)));
        assert!(!models_are_equal(Some(&a), None));
    }

    /// Non-reasoning models advertise exactly `[off]`; reasoning models
    /// without an explicit map admit every tier and fall back to the
    /// substring `supports_xhigh` heuristic for the top slot.
    #[test]
    fn get_supported_thinking_levels_uses_substring_default_when_map_missing() {
        // Non-reasoning -> only off.
        let mut non_reasoning = test_model("gpt-4o", Provider::OpenAI);
        non_reasoning.reasoning = false;
        assert_eq!(get_supported_thinking_levels(&non_reasoning), vec![None]);

        // Reasoning, xhigh-substring -> all six levels.
        let mut xhigh_model = test_model("gpt-5.3-mini", Provider::OpenAI);
        xhigh_model.reasoning = true;
        let levels = get_supported_thinking_levels(&xhigh_model);
        assert_eq!(
            levels,
            vec![
                None,
                Some(ThinkingLevel::Minimal),
                Some(ThinkingLevel::Low),
                Some(ThinkingLevel::Medium),
                Some(ThinkingLevel::High),
                Some(ThinkingLevel::Xhigh),
            ]
        );

        // Reasoning, no xhigh substring -> xhigh excluded.
        let mut no_xhigh = test_model("claude-sonnet-4", Provider::Anthropic);
        no_xhigh.reasoning = true;
        let levels = get_supported_thinking_levels(&no_xhigh);
        assert!(!levels.contains(&Some(ThinkingLevel::Xhigh)));
        assert!(levels.contains(&Some(ThinkingLevel::High)));
        assert!(levels.contains(&None));
    }

    /// An explicit `thinking_level_map` is authoritative — a `null`
    /// entry marks the level unsupported; an omitted key drops the
    /// xhigh slot but admits the other tiers.
    #[test]
    fn get_supported_thinking_levels_respects_explicit_map() {
        let mut model = test_model("custom", Provider::OpenAI);
        model.reasoning = true;
        let mut map = std::collections::HashMap::new();
        map.insert("off".to_string(), Some("off".to_string()));
        map.insert("minimal".to_string(), Some("minimal".to_string()));
        map.insert("low".to_string(), Some("low".to_string()));
        map.insert("medium".to_string(), None); // marked unsupported
        map.insert("high".to_string(), Some("high".to_string()));
        // xhigh deliberately omitted -> excluded.
        model.thinking_level_map = Some(map);

        let levels = get_supported_thinking_levels(&model);
        assert_eq!(
            levels,
            vec![
                None,
                Some(ThinkingLevel::Minimal),
                Some(ThinkingLevel::Low),
                Some(ThinkingLevel::High),
            ],
            "medium must be dropped (null) and xhigh must be dropped (missing): {levels:?}",
        );
    }

    /// `clamp_thinking_level` walks up first, then back down — so an
    /// unsupported request rises to the next available tier rather than
    /// dropping straight to `off`.
    #[test]
    fn clamp_thinking_level_walks_up_then_down() {
        let mut model = test_model("custom", Provider::OpenAI);
        model.reasoning = true;
        let mut map = std::collections::HashMap::new();
        map.insert("off".to_string(), Some("off".to_string()));
        // Mark minimal/low explicitly unsupported (null).
        map.insert("minimal".to_string(), None);
        map.insert("low".to_string(), None);
        map.insert("medium".to_string(), Some("medium".to_string()));
        map.insert("high".to_string(), Some("high".to_string()));
        // xhigh omitted -> excluded (upstream "missing key" rule).
        model.thinking_level_map = Some(map);

        // low -> walk up over the null gap -> medium.
        assert_eq!(
            clamp_thinking_level(&model, Some(ThinkingLevel::Low)),
            Some(ThinkingLevel::Medium)
        );
        // xhigh -> walk up off the end, then down -> high.
        assert_eq!(
            clamp_thinking_level(&model, Some(ThinkingLevel::Xhigh)),
            Some(ThinkingLevel::High)
        );
        // off stays off (explicitly supported).
        assert_eq!(clamp_thinking_level(&model, None), None);
    }

    /// Non-reasoning models clamp every request to `off`.
    #[test]
    fn clamp_thinking_level_collapses_to_off_for_non_reasoning_models() {
        let mut model = test_model("gpt-4o", Provider::OpenAI);
        model.reasoning = false;
        for level in [
            None,
            Some(ThinkingLevel::Minimal),
            Some(ThinkingLevel::Low),
            Some(ThinkingLevel::Medium),
            Some(ThinkingLevel::High),
            Some(ThinkingLevel::Xhigh),
        ] {
            assert_eq!(
                clamp_thinking_level(&model, level),
                None,
                "non-reasoning model must clamp {level:?} to off"
            );
        }
    }
}
